### ISSUE TITLE
Rotor III error

### ISSUE THREAD

**Issue by 0bs72** [maxime1992/my-dev.to#76]
I'm a noob to the GitHub process and as such I don't yet understand the PR process; sorry.

What I do know (because I've been working on a Enigma I sim) is that in P1 of your excellent blog post, under **Alphabet and index** you have:

- Rotor 3: `fvpjiaoyedrzxwgctkuqsbnmhl`

... which is incorrect. That is in fact the wiring for Reflector UKW-C.

The correct wiring for Rotor 3 is: `B D F H J L C P R T X V Z N Y E I W G A K M U S Q O`

With my best regards and due respect.

**Comment by maxime1992** [comment]
> I'm a noob to the GitHub process and as such I don't yet understand the PR process; sorry.

No worries at all, I only mentioned the possibility to raise a PR so that people used to it could make a fix directly instead of mentioning it on the blog post :).

> is that in P1 of your excellent blog post

:heart: :pray: 

> which is incorrect. That is in fact the wiring for Reflector UKW-C.

I don't remember whether I even tried to use the correct ones or if I picked something completely random. The point here was just to give an example of how the letters could be scrambled.

I think it still makes sense to understand the article further while not being historically accurate and I don't have the time nor motivation anymore to fix this to ensure the rest of the article remains coherent if I change that line. So good to know but sorry I won't fix it.

Don't get me wrong though, your comment is much appreciated :) 

Thanks a lot and I hope you had great fun working on Enigma I sim on your side :star_struck:!
